package com.kiksoft.kikservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLQDTEMIN_IHALE_BILGISI extends AttributeContainer implements KvmSerializable
{

    public String DOSYA_TIPI;

    public String DOKUMANID;

    public String DOSYA_NUMARASI;

    public String ISIN_TANIMI;

    public String ISIN_TURU;

    public String IHALE_KAYIT_NUMARASI;

    public String TALEP_EDEN_BIRIM;

    public String TALEP_EVRAK_NO;

    public String TALEP_EVRAK_TARIHI;

    public String ALIM_ZAMANI;

    public String IDARENIN_ADI;

    public String DURUMU;

    public String GOREVLI;

    public String TEKLIF_SOZLESME_TURU;

    public String KISMI_ISIN_TAMAMI;

    public String KATEGORI;

    public String YAKLASIK_MALIYET;

    public String USULU;

    public Integer ALIMDAKI_TOPLAM_KALEM_SAYISI=0;

    public Integer TEKLIF_VERILMEYEN_KALEM_SAYISI=0;

    public Integer ALINAMAYAN_KALEM_SAYISI=0;

    public Integer TOPLAM_TEKLIF_SAYISI=0;

    public Integer GECERLI_TEKLIF_SAYISI=0;

    public String AVANTAJLI_TEKLIFLER;

    public Integer ITIRAZLI_KALEM_SAYISI=0;

    public String SOZLESME_TOPLAM;

    private transient java.lang.Object __source;




    public void loadFromSoap(java.lang.Object paramObj,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj;

        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            }
        }



    }


    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DOSYA_TIPI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOSYA_TIPI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOSYA_TIPI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DOKUMANID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOKUMANID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOKUMANID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DOSYA_NUMARASI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOSYA_NUMARASI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOSYA_NUMARASI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN_TANIMI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN_TANIMI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN_TANIMI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN_TURU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN_TURU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN_TURU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IHALE_KAYIT_NUMARASI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IHALE_KAYIT_NUMARASI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IHALE_KAYIT_NUMARASI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TALEP_EDEN_BIRIM"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TALEP_EDEN_BIRIM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TALEP_EDEN_BIRIM = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TALEP_EVRAK_NO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TALEP_EVRAK_NO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TALEP_EVRAK_NO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TALEP_EVRAK_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TALEP_EVRAK_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TALEP_EVRAK_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ALIM_ZAMANI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ALIM_ZAMANI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ALIM_ZAMANI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IDARENIN_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IDARENIN_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IDARENIN_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DURUMU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DURUMU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DURUMU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GOREVLI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GOREVLI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GOREVLI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TEKLIF_SOZLESME_TURU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TEKLIF_SOZLESME_TURU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TEKLIF_SOZLESME_TURU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("KISMI_ISIN_TAMAMI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.KISMI_ISIN_TAMAMI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.KISMI_ISIN_TAMAMI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("KATEGORI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.KATEGORI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.KATEGORI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("YAKLASIK_MALIYET"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.YAKLASIK_MALIYET = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.YAKLASIK_MALIYET = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("USULU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.USULU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.USULU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ALIMDAKI_TOPLAM_KALEM_SAYISI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ALIMDAKI_TOPLAM_KALEM_SAYISI = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ALIMDAKI_TOPLAM_KALEM_SAYISI = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TEKLIF_VERILMEYEN_KALEM_SAYISI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TEKLIF_VERILMEYEN_KALEM_SAYISI = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.TEKLIF_VERILMEYEN_KALEM_SAYISI = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ALINAMAYAN_KALEM_SAYISI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ALINAMAYAN_KALEM_SAYISI = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ALINAMAYAN_KALEM_SAYISI = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TOPLAM_TEKLIF_SAYISI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TOPLAM_TEKLIF_SAYISI = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.TOPLAM_TEKLIF_SAYISI = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GECERLI_TEKLIF_SAYISI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GECERLI_TEKLIF_SAYISI = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.GECERLI_TEKLIF_SAYISI = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AVANTAJLI_TEKLIFLER"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AVANTAJLI_TEKLIFLER = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AVANTAJLI_TEKLIFLER = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ITIRAZLI_KALEM_SAYISI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ITIRAZLI_KALEM_SAYISI = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ITIRAZLI_KALEM_SAYISI = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_TOPLAM"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_TOPLAM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_TOPLAM = (String)obj;
                }
            }
            return true;
        }
        return false;
    }

    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }


    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DOSYA_TIPI;
        }
        if(propertyIndex==1)
        {
            return DOKUMANID;
        }
        if(propertyIndex==2)
        {
            return DOSYA_NUMARASI;
        }
        if(propertyIndex==3)
        {
            return ISIN_TANIMI;
        }
        if(propertyIndex==4)
        {
            return ISIN_TURU;
        }
        if(propertyIndex==5)
        {
            return IHALE_KAYIT_NUMARASI;
        }
        if(propertyIndex==6)
        {
            return TALEP_EDEN_BIRIM;
        }
        if(propertyIndex==7)
        {
            return TALEP_EVRAK_NO;
        }
        if(propertyIndex==8)
        {
            return TALEP_EVRAK_TARIHI;
        }
        if(propertyIndex==9)
        {
            return ALIM_ZAMANI;
        }
        if(propertyIndex==10)
        {
            return IDARENIN_ADI;
        }
        if(propertyIndex==11)
        {
            return DURUMU;
        }
        if(propertyIndex==12)
        {
            return GOREVLI;
        }
        if(propertyIndex==13)
        {
            return TEKLIF_SOZLESME_TURU;
        }
        if(propertyIndex==14)
        {
            return KISMI_ISIN_TAMAMI;
        }
        if(propertyIndex==15)
        {
            return KATEGORI;
        }
        if(propertyIndex==16)
        {
            return YAKLASIK_MALIYET;
        }
        if(propertyIndex==17)
        {
            return USULU;
        }
        if(propertyIndex==18)
        {
            return ALIMDAKI_TOPLAM_KALEM_SAYISI;
        }
        if(propertyIndex==19)
        {
            return TEKLIF_VERILMEYEN_KALEM_SAYISI;
        }
        if(propertyIndex==20)
        {
            return ALINAMAYAN_KALEM_SAYISI;
        }
        if(propertyIndex==21)
        {
            return TOPLAM_TEKLIF_SAYISI;
        }
        if(propertyIndex==22)
        {
            return GECERLI_TEKLIF_SAYISI;
        }
        if(propertyIndex==23)
        {
            return AVANTAJLI_TEKLIFLER;
        }
        if(propertyIndex==24)
        {
            return ITIRAZLI_KALEM_SAYISI;
        }
        if(propertyIndex==25)
        {
            return SOZLESME_TOPLAM;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 26;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOSYA_TIPI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOKUMANID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOSYA_NUMARASI";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN_TANIMI";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN_TURU";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IHALE_KAYIT_NUMARASI";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TALEP_EDEN_BIRIM";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TALEP_EVRAK_NO";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TALEP_EVRAK_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ALIM_ZAMANI";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IDARENIN_ADI";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DURUMU";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GOREVLI";
            info.namespace= "";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TEKLIF_SOZLESME_TURU";
            info.namespace= "";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "KISMI_ISIN_TAMAMI";
            info.namespace= "";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "KATEGORI";
            info.namespace= "";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "YAKLASIK_MALIYET";
            info.namespace= "";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "USULU";
            info.namespace= "";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ALIMDAKI_TOPLAM_KALEM_SAYISI";
            info.namespace= "";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TEKLIF_VERILMEYEN_KALEM_SAYISI";
            info.namespace= "";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ALINAMAYAN_KALEM_SAYISI";
            info.namespace= "";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TOPLAM_TEKLIF_SAYISI";
            info.namespace= "";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "GECERLI_TEKLIF_SAYISI";
            info.namespace= "";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AVANTAJLI_TEKLIFLER";
            info.namespace= "";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ITIRAZLI_KALEM_SAYISI";
            info.namespace= "";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_TOPLAM";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


}