package com.kiksoft.kikservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLQIS_ARTIS extends AttributeContainer implements KvmSerializable
{
    
    public String DOKUMANID;
    
    public String IDARENIN_ADI;
    
    public String TARIH;
    
    public String SOZLESME_NO;
    
    public String SOZLESME_BASLANGIC_TARIHI;
    
    public String SOZLESME_BITIS_TARIHI;
    
    public String ISIN_TANIMI;
    
    public String FIRMA;
    
    public String GOREVLI;
    
    public String IHALE_USULU;
    
    public String IHALE_KAYIT_NUMARASI;
    
    public String DURUMU;
    
    public String TOPLAM_ARTIRIM_TUTARI;
        
    private transient java.lang.Object __source;    
    

    
    
    public void loadFromSoap(java.lang.Object paramObj,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DOKUMANID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOKUMANID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOKUMANID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IDARENIN_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IDARENIN_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IDARENIN_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TARIH"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TARIH = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TARIH = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_NO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_NO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_NO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_BASLANGIC_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_BASLANGIC_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_BASLANGIC_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_BITIS_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_BITIS_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_BITIS_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN_TANIMI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN_TANIMI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN_TANIMI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FIRMA"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FIRMA = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FIRMA = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GOREVLI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GOREVLI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GOREVLI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IHALE_USULU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IHALE_USULU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IHALE_USULU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IHALE_KAYIT_NUMARASI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IHALE_KAYIT_NUMARASI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IHALE_KAYIT_NUMARASI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DURUMU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DURUMU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DURUMU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TOPLAM_ARTIRIM_TUTARI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TOPLAM_ARTIRIM_TUTARI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TOPLAM_ARTIRIM_TUTARI = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DOKUMANID;
        }
        if(propertyIndex==1)
        {
            return IDARENIN_ADI;
        }
        if(propertyIndex==2)
        {
            return TARIH;
        }
        if(propertyIndex==3)
        {
            return SOZLESME_NO;
        }
        if(propertyIndex==4)
        {
            return SOZLESME_BASLANGIC_TARIHI;
        }
        if(propertyIndex==5)
        {
            return SOZLESME_BITIS_TARIHI;
        }
        if(propertyIndex==6)
        {
            return ISIN_TANIMI;
        }
        if(propertyIndex==7)
        {
            return FIRMA;
        }
        if(propertyIndex==8)
        {
            return GOREVLI;
        }
        if(propertyIndex==9)
        {
            return IHALE_USULU;
        }
        if(propertyIndex==10)
        {
            return IHALE_KAYIT_NUMARASI;
        }
        if(propertyIndex==11)
        {
            return DURUMU;
        }
        if(propertyIndex==12)
        {
            return TOPLAM_ARTIRIM_TUTARI;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 13;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOKUMANID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IDARENIN_ADI";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TARIH";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_NO";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_BASLANGIC_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_BITIS_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN_TANIMI";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FIRMA";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GOREVLI";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IHALE_USULU";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IHALE_KAYIT_NUMARASI";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DURUMU";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TOPLAM_ARTIRIM_TUTARI";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
