package com.kiksoft.kikservice;


//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface NLQIServiceEvents
{
    void Starting();
    void Completed(NLQOperationResult result);
}
