package com.kiksoft.kikservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLQSOZLESME_DETAYI extends AttributeContainer implements KvmSerializable
{
    
    public String DOSYA_NUMARASI;
    
    public String DOKUMANID;
    
    public String IHALE_KAYIT_NO;
    
    public String ISIN_ADI;
    
    public String FIRMA_ADI;
    
    public String FIRMA_ADRESI;
    
    public String FIRMA_TELEFONU;
    
    public String TOPLAM_IS_ARTIS_TUTARI;
    
    public String SOZLESME_BASLANGIC_TARIHI;
    
    public String SOZLESME_BITIS_TARIHI;
    
    public String SOZLESME_TOPLAMI;
    
    public String GOREVLI;
        
    private transient java.lang.Object __source;    
    

    
    
    public void loadFromSoap(java.lang.Object paramObj,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DOSYA_NUMARASI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOSYA_NUMARASI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOSYA_NUMARASI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DOKUMANID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOKUMANID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOKUMANID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IHALE_KAYIT_NO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IHALE_KAYIT_NO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IHALE_KAYIT_NO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FIRMA_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FIRMA_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FIRMA_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FIRMA_ADRESI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FIRMA_ADRESI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FIRMA_ADRESI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FIRMA_TELEFONU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FIRMA_TELEFONU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FIRMA_TELEFONU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TOPLAM_IS_ARTIS_TUTARI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TOPLAM_IS_ARTIS_TUTARI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TOPLAM_IS_ARTIS_TUTARI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_BASLANGIC_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_BASLANGIC_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_BASLANGIC_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_BITIS_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_BITIS_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_BITIS_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_TOPLAMI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_TOPLAMI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_TOPLAMI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GOREVLI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GOREVLI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GOREVLI = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DOSYA_NUMARASI;
        }
        if(propertyIndex==1)
        {
            return DOKUMANID;
        }
        if(propertyIndex==2)
        {
            return IHALE_KAYIT_NO;
        }
        if(propertyIndex==3)
        {
            return ISIN_ADI;
        }
        if(propertyIndex==4)
        {
            return FIRMA_ADI;
        }
        if(propertyIndex==5)
        {
            return FIRMA_ADRESI;
        }
        if(propertyIndex==6)
        {
            return FIRMA_TELEFONU;
        }
        if(propertyIndex==7)
        {
            return TOPLAM_IS_ARTIS_TUTARI;
        }
        if(propertyIndex==8)
        {
            return SOZLESME_BASLANGIC_TARIHI;
        }
        if(propertyIndex==9)
        {
            return SOZLESME_BITIS_TARIHI;
        }
        if(propertyIndex==10)
        {
            return SOZLESME_TOPLAMI;
        }
        if(propertyIndex==11)
        {
            return GOREVLI;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOSYA_NUMARASI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOKUMANID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IHALE_KAYIT_NO";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN_ADI";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FIRMA_ADI";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FIRMA_ADRESI";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FIRMA_TELEFONU";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TOPLAM_IS_ARTIS_TUTARI";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_BASLANGIC_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_BITIS_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_TOPLAMI";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GOREVLI";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
