package com.kiksoft.kikservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLQSIPARIS_BILGISI extends AttributeContainer implements KvmSerializable
{
    
    public String FIRMA_ADI;
    
    public String DOKUMANID;
    
    public String IDARE_ADI;
    
    public String SOZLESME_NO;
    
    public String GOREVLI;
    
    public String SIPARIS_TARIHI;
    
    public String PARTI_NO;
    
    public String SIPARIS_DURUMU;
    
    public String ACIKLAMA;
        
    private transient java.lang.Object __source;    
    

    
    
    public void loadFromSoap(java.lang.Object paramObj,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("FIRMA_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FIRMA_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FIRMA_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DOKUMANID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOKUMANID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOKUMANID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IDARE_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IDARE_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IDARE_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SOZLESME_NO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SOZLESME_NO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SOZLESME_NO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GOREVLI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GOREVLI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GOREVLI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SIPARIS_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SIPARIS_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SIPARIS_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PARTI_NO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PARTI_NO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.PARTI_NO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SIPARIS_DURUMU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SIPARIS_DURUMU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SIPARIS_DURUMU = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ACIKLAMA"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ACIKLAMA = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ACIKLAMA = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return FIRMA_ADI;
        }
        if(propertyIndex==1)
        {
            return DOKUMANID;
        }
        if(propertyIndex==2)
        {
            return IDARE_ADI;
        }
        if(propertyIndex==3)
        {
            return SOZLESME_NO;
        }
        if(propertyIndex==4)
        {
            return GOREVLI;
        }
        if(propertyIndex==5)
        {
            return SIPARIS_TARIHI;
        }
        if(propertyIndex==6)
        {
            return PARTI_NO;
        }
        if(propertyIndex==7)
        {
            return SIPARIS_DURUMU;
        }
        if(propertyIndex==8)
        {
            return ACIKLAMA;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 9;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FIRMA_ADI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOKUMANID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IDARE_ADI";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOZLESME_NO";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GOREVLI";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SIPARIS_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PARTI_NO";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SIPARIS_DURUMU";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ACIKLAMA";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
