package com.kiksoft.kikservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLQTEKLIF extends AttributeContainer implements KvmSerializable
{
    
    public String KALEM_ADI;
    
    public String FIRMA;
    
    public String MIKTAR;
    
    public String BIRIM;
    
    public String BIRIM_FIYAT;
    
    public String MALIYET;
    
    public String TOPLAM_TUTAR;
        
    private transient java.lang.Object __source;    
    

    
    
    public void loadFromSoap(java.lang.Object paramObj,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("KALEM_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.KALEM_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.KALEM_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FIRMA"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FIRMA = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FIRMA = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MIKTAR"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MIKTAR = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MIKTAR = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BIRIM"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BIRIM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BIRIM = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BIRIM_FIYAT"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BIRIM_FIYAT = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BIRIM_FIYAT = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MALIYET"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MALIYET = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MALIYET = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TOPLAM_TUTAR"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TOPLAM_TUTAR = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TOPLAM_TUTAR = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return KALEM_ADI;
        }
        if(propertyIndex==1)
        {
            return FIRMA;
        }
        if(propertyIndex==2)
        {
            return MIKTAR;
        }
        if(propertyIndex==3)
        {
            return BIRIM;
        }
        if(propertyIndex==4)
        {
            return BIRIM_FIYAT;
        }
        if(propertyIndex==5)
        {
            return MALIYET;
        }
        if(propertyIndex==6)
        {
            return TOPLAM_TUTAR;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "KALEM_ADI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FIRMA";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MIKTAR";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BIRIM";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BIRIM_FIYAT";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MALIYET";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TOPLAM_TUTAR";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
