package com.kiksoft.kikservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.6.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NLQTALEP_BILGISI extends AttributeContainer implements KvmSerializable
{
    
    public String IDARENIN_ADI;
    
    public String DOSYA_NUMARASI;
    
    public String ISIN_TANIMI;
    
    public String ASAMA;
    
    public String TALEP_EDEN_BIRIM;
    
    public String TALEP_EVRAK_NO;
    
    public String TALEP_EVRAK_TARIHI;
    
    public String GOREVLI;
    
    public String DOKUMANID;
    
    public String KATEGORI;
    
    public String ISIN_TURU;
        
    private transient java.lang.Object __source;    
    

    
    
    public void loadFromSoap(java.lang.Object paramObj,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,NLQExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IDARENIN_ADI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IDARENIN_ADI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IDARENIN_ADI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DOSYA_NUMARASI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOSYA_NUMARASI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOSYA_NUMARASI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN_TANIMI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN_TANIMI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN_TANIMI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ASAMA"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ASAMA = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ASAMA = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TALEP_EDEN_BIRIM"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TALEP_EDEN_BIRIM = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TALEP_EDEN_BIRIM = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TALEP_EVRAK_NO"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TALEP_EVRAK_NO = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TALEP_EVRAK_NO = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TALEP_EVRAK_TARIHI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TALEP_EVRAK_TARIHI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TALEP_EVRAK_TARIHI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GOREVLI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GOREVLI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GOREVLI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DOKUMANID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DOKUMANID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DOKUMANID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("KATEGORI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.KATEGORI = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.KATEGORI = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN_TURU"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN_TURU = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN_TURU = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return IDARENIN_ADI;
        }
        if(propertyIndex==1)
        {
            return DOSYA_NUMARASI;
        }
        if(propertyIndex==2)
        {
            return ISIN_TANIMI;
        }
        if(propertyIndex==3)
        {
            return ASAMA;
        }
        if(propertyIndex==4)
        {
            return TALEP_EDEN_BIRIM;
        }
        if(propertyIndex==5)
        {
            return TALEP_EVRAK_NO;
        }
        if(propertyIndex==6)
        {
            return TALEP_EVRAK_TARIHI;
        }
        if(propertyIndex==7)
        {
            return GOREVLI;
        }
        if(propertyIndex==8)
        {
            return DOKUMANID;
        }
        if(propertyIndex==9)
        {
            return KATEGORI;
        }
        if(propertyIndex==10)
        {
            return ISIN_TURU;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IDARENIN_ADI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOSYA_NUMARASI";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN_TANIMI";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ASAMA";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TALEP_EDEN_BIRIM";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TALEP_EVRAK_NO";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TALEP_EVRAK_TARIHI";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GOREVLI";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DOKUMANID";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "KATEGORI";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN_TURU";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
